######################################################################
# Automatically generated by qmake (2.01a) Tue May 10 11:27:43 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += iconloader.h qdeclarativefolderlistmodel.h
SOURCES += iconloader.cpp plugin.cpp qdeclarativefolderlistmodel.cpp
